services:
  task_db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    profiles:
      - taskDB