spring:
  sql:
    init:
      mode: never

  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/taskManager_DB
    driver-class-name: org.postgresql.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    show-sql: true

server:
  port: 8080
  address: 0.0.0.0