spring:
  sql:
    init:
      mode: never

  docker:
    compose:
      profiles:
        active: taskDB
      lifecycle-management: start_and_stop
      start:
        command: up
      stop:
        command: stop

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    show-sql: true

server:
  port: 8080
  address: 0.0.0.0