CREATE TABLE users (
                       user_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       username VARCHAR(50) UNIQUE NOT NULL,
                       email VARCHAR(100) UNIQUE NOT NULL,
                       password varchar NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tasks (
                       task_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       title VARCHAR(255) NOT NULL,
                       description VARCHAR(255),
                       status VARCHAR(50) NOT NULL DEFAULT 'open', -- например: open, in_progress, done, closed
                       author_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                       executor_id INT REFERENCES users(user_id) ON DELETE SET NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
                          comment_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          task_id INT NOT NULL REFERENCES tasks(task_id) ON DELETE CASCADE,
                          author_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
                          content varchar NOT NULL,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);