CREATE TABLE comments (
      comment_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      task_id INT NOT NULL REFERENCES tasks(task_id) ON DELETE CASCADE,
      author_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
      content varchar NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);